django_backend/lms_project/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('main.urls')),  # Include the URLs of the main app
    # path('module/', include('module.urls')),         # For module-related views
    path('module_group/', include('module_group.urls')),  
    path('user/', include('user.urls')),             # For user-related views
    path('user_module/', include('user_module.urls')), # For user-module assignments
    path('category/', include('category.urls')),  
    path('question/', include('question.urls')),  
    # path('quiz/', include('quiz.urls')),  
    path('role/', include('role.urls')),  
    path('subject/', include('subject.urls')),  
    path('training_program/', include('training_program.urls')),  
    path('training_program_subjects/', include('training_program_subjects.urls')),    
    
    path('course/', include('course.urls')),  

    path('tools/', include('tools.urls')),  
    # Add more paths for other new apps here
]

django_backend/main/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views  # Import your views from the main app

from django.conf import settings
from django.conf.urls.static import static


app_name = 'main'

urlpatterns = [
    # Your other URL patterns
    path('', views.home, name='home'),
    # Authentication URLs
    path('login/', auth_views.LoginView.as_view(template_name='login.html', next_page='/'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='logout.html', next_page='login'), name='logout'),
    path('logout/', views.logout_view, name="logout"),
    path('run_setup/', views.run_setup, name="run_setup"),
]

django_backend/question/urls.py
from django.urls import path
from . import views

app_name = 'question'

urlpatterns = [
    path('', views.question_list, name='question_list'),
    path('<int:pk>/', views.question_detail, name='question_detail'),
    path('add/', views.question_add, name='question_add'),
    path('<int:pk>/edit/', views.question_edit, name='question_edit'),
    path('<int:pk>/delete/', views.question_delete, name='question_delete'),
    path('<int:pk>/answer_add/', views.question_add, name='answer_add'),
]

django_backend/question/models.py
from django.db import models
from category.models import Category
from subject.models import Subject
from django.utils import timezone

class Question(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

django_backend/question/forms.py
from django import forms
from .models import Question, Answer, Category
from django.forms import modelformset_factory, inlineformset_factory

# Form for creating and editing questions
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'category', 'question_text']

# Form for creating and editing answers
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'is_correct']

# Formset for handling multiple answers per question
AnswerFormSet = inlineformset_factory(Question, Answer, form=AnswerForm, extra=1)

# Formset for handling multiple questions
QuestionFormSet = modelformset_factory(Question, form=QuestionForm, extra=1)

django_backend/question/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .models import Question, Answer
from .forms import QuestionForm, AnswerForm
from module_group.models import ModuleGroup
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Question views
from main.utils.block import block_student
from django.contrib.auth.decorators import user_passes_test


@login_required
@user_passes_test(block_student)
def question_list(request):
    module_groups = ModuleGroup.objects.all()
    
    questions = Question.objects.all()
    
    questions_and_correct_answers = {}

    for question in questions:
        correct_answers = Answer.objects.filter(question_id = question.id, is_correct= True)
        
        questions_and_correct_answers[question.id] = {
            'question' : question,
            'correct_answers' : correct_answers
        }

    # print(questions_and_correct_answers)
    context = {
        'questions': questions,
        'module_groups': module_groups,
        'correct_answers': None,
        'questions_and_correct_answers': questions_and_correct_answers,
    }
    return render(request, 'question_list.html', context)

@login_required
@user_passes_test(block_student)
def question_detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    return render(request, 'question_detail.html', {'question': question})

@login_required
@user_passes_test(block_student)
def question_add(request):
    if request.method == 'POST':
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            question = question_form.save()
            answer_texts = request.POST.getlist('answer_text[]')
            is_position_corrects = request.POST.getlist('is_correct[]')

            is_corrects = [False]*len(answer_texts)

            for is_position_correct in is_position_corrects:
                is_corrects[int(is_position_correct)] = True
     
            for i in range(len(answer_texts)):
                Answer.objects.create(
                    question=question,
                    text=answer_texts[i],
                    is_correct=is_corrects[i]
                )

            return redirect('/question')
    else:
        question_form = QuestionForm()
    return render(request, 'question_add.html', {'question_form': question_form})

@login_required
@user_passes_test(block_student)
def question_edit(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect('question_list')
    else:
        form = QuestionForm(instance=question)
    return render(request, 'question_form.html', {'form': form})

@login_required
@user_passes_test(block_student)
def question_delete(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == 'POST':
        question.delete()
        return redirect('question:question_list')
    
    context = {
        'name': question.question_text,
        'cancel_link': reverse('question:question_list')
    }
    return render(request, 'confirm_delete.html', context)

django_backend/question/templates/answer_form.html
{% extends 'base.html' %}
{% load form_filters %}

{% block title %}Add Answer{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Add Answer to "{{ question.question_text }}"</h2>
    <form method="post" class="mt-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.text.id_for_label }}">Text</label>
            {{ form.text|add_class:"form-control" }}
        </div>
        <div class="form-group">
            <label for="{{ form.is_correct.id_for_label }}">Is Correct</label>
            {{ form.is_correct|add_class:"form-check-input" }}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'question_detail' question.pk %}" class="btn btn-secondary">Back to Question</a>
    </form>
</div>
{% endblock %}

django_backend/question/templates/category_detail.html
{% extends 'base.html' %}

{% block title %}Category Detail{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Category: {{ category.name }}</h2>
    <p>Here you can display more details about this category.</p>
    
    <a href="{% url 'question_list' %}" class="btn btn-primary">Back to Question List</a>
</div>
{% endblock %}

django_backend/question/templates/question_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h2>Add Questions</h2>
    <form method="post">
        {% csrf_token %}

        <!-- Question Form -->
        <div class="form-group">
            {% comment %} <label for="subject">Subject</label> {% endcomment %}
            {{ question_form.subject|as_crispy_field }}
        </div>
        <div class="form-group">
            {% comment %} <label for="category">Category</label> {% endcomment %}
            {{ question_form.category|as_crispy_field }}
        </div>
        <div class="form-group">
            {% comment %} <label for="question_text">Question</label> {% endcomment %}
            {{ question_form.question_text|as_crispy_field }}
        </div>

        <!-- Answer Formset -->
        <h4>Answers</h4>
        <div id="answers-formset">
            <div class="answer-group form-group">
                <label for="answer_text">Answer</label>
                <input type="text" name="answer_text[]" class="form-control" placeholder="Enter answer text" required>
                <input type="checkbox" name="is_correct[]" value="0" class="form-check-input ml-2">
                <label for="is_correct" class="ml-4">Correct</label>
            </div>
        </div>
        <button type="button" class="btn btn-secondary add-answer">Add Answer</button>
        <hr>
        
        <button type="submit" class="btn btn-success">Save Questions</button>
    </form>
</div>

<script>
    var answer_num = 0;

    document.querySelector('.add-answer').addEventListener('click', function() {
        var formset = document.getElementById('answers-formset');
        answer_num += 1;
        var newAnswerGroup = `
            <div class="answer-group form-group">
                <label for="answer_text">Answer</label>
                <input type="text" name="answer_text[]" class="form-control" placeholder="Enter answer text" required>
                <input type="checkbox" name="is_correct[]" value='${answer_num}' class="form-check-input ml-2">
                <label for="is_correct" class="ml-4">Correct</label>
            </div>
        `;
        
        // Append the new answer fields to the answers formset
        formset.insertAdjacentHTML('beforeend', newAnswerGroup);
    });
</script>
{% endblock %}

django_backend/question/templates/question_confim_delete.html
{% extends 'base.html' %}

{% block title %}Delete Question{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Are you sure you want to delete the question "{{ question.question_text }}"?</h2>
    
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'question_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

django_backend/question/templates/question_detail.html
{% extends 'base.html' %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}
<h2>{{ question.question_text }}</h2>
<p><strong>Created At:</strong> {{ question.created_at }}</p>
<p><strong>Correct Answer:</strong> {{ question.correct_answer }}</p>
<!-- Hiển thị Subject -->
<p><strong>Subject:</strong> 
    {% if question.subject %}
        {{ question.subject.name }}
    {% else %}
        No Subject
    {% endif %}
</p>

<!-- Hiển thị Category -->
<p><strong>Category:</strong> 
    {% if question.category %}
        {{ question.category.name }}
    {% else %}
        No Category
    {% endif %}
</p>
<h3>Answers</h3>
<ul class="list-group">
    {% for answer in question.answers.all %}
    <li class="list-group-item">
        {{ answer.text }}{% if answer.is_correct %} <span class="badge badge-success">Correct</span>{% endif %}
    </li>
    {% empty %}
    <li class="list-group-item">No answers yet.</li>
    {% endfor %}
</ul>
<a href="{% url 'question_list' %}" class="btn btn-secondary">Back to List</a>
{% endblock %}

django_backend/question/templates/question_form.html
{% extends 'base.html' %}
{% load form_filters %}

{% block title %}Question Form{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">{% if form.instance.pk %}Edit Question 1111{% else %}Add New Question{% endif %}</h2>
    
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        
        <div class="form-group">
            {{ form.non_field_errors }}
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {{ field|add_class:"form-control" }}
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% if field.errors %}
                        <div class="text-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        
        <div class="d-flex justify-content-between mt-4">
            <a href="{% url 'question_list' %}" class="btn btn-secondary">Back to Question List</a>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>
{% endblock %}

django_backend/question/templates/question_list.html
{% extends 'base.html' %}

{% block title %}Question List{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Question List</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Question</th>
                <th>Correct Answer</th>
                <th>Subject</th>
                <th>Category</th>
                <th>Date Created</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for id, question_and_correct_answer in questions_and_correct_answers.items %}
            <tr>
                <td>{{ question_and_correct_answer.question.question_text }}</td>
                {% comment %} <td>nah</td> {% endcomment %}
                <td>
                    {% if question_and_correct_answer.correct_answers %}
                            {% for correct_answer in question_and_correct_answer.correct_answers%}
                                <p>- {{ correct_answer }}</p> 
                            {% endfor%}
                        {% else %}
                        <div class="alert alert-danger" role="alert">
                            None!
                        </div>
                    {% endif %}
                </td>
                <td>
                    {% if question_and_correct_answer.question.subject %}
                        {{ question_and_correct_answer.question.subject }}
                    {% else %}
                        No Subject
                    {% endif %}
                </td>
                <td>
                    {% if question_and_correct_answer.question.category %}
                        {{ question_and_correct_answer.question.category }}
                    {% else %}
                        No Category
                    {% endif %}
                </td>
                <td>{{ question_and_correct_answer.question.created_at }}</td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                          Actions
                        </button>
                        <div class="dropdown-menu">
                            <a href="{% url 'question:question_detail' question_and_correct_answer.question.pk %}" class="dropdown-item">View</a>
                            <a href="{% url 'question:question_edit' question_and_correct_answer.question.pk %}" class="btn btn-warning dropdown-item">Edit</a>
                            <a href="{% url 'question:answer_add' question_and_correct_answer.question.pk %}" class="btn btn-primary dropdown-item">Add Answer</a>
                            <a href="{% url 'question:question_delete' question_and_correct_answer.question.pk %}" class="btn btn-primary dropdown-item">Delete</a>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'question:question_add' %}" class="btn btn-success">Add New Question</a>
</div>
{% endblock %}

django_backend/question/templates/subject_detail.html
{% extends 'base.html' %}

{% block title %}Subject Detail{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>Subject: {{ subject.name }}</h2>
    <p>Here you can display more details about this subject.</p>
    
    <a href="{% url 'question_list' %}" class="btn btn-primary">Back to Question List</a>
</div>
{% endblock %}