django_backend/course/urls.py
from django.urls import path
from .views import course_management
from .views import sub_course_management
from .views import module_management
from .views import sub_module_management
from .views import quiz_management
from .views import quiz_report_management
from .views import question_management
from .views import answer_management
from .views import course_operations
from .views import quiz_operations
from .views import image_management

from .views import logger
app_name = 'course'

urlpatterns = [
    path('course_list',course_management.course_list,name='course_list'),

    path('upload_existed_course/',course_management.upload_existed_course,name='upload_existed_course'),
    path('course_add/',course_management.course_add,name='course_add'),
    path('course_edit/<int:course_pk>/',course_management.course_edit,name='course_edit'),
    path('course_delete/<int:course_pk>/',course_management.course_delete,name='course_delete'),
    path('<int:course_pk>/course_view/',course_management.course_view,name='course_view'),

    path('<int:course_pk>/image_list/',image_management.image_list,name='image_list'),
    path('<int:course_pk>/image_add/',image_management.image_add,name='image_add'),
    path('<int:course_pk>/image/<int:image_pk>/delete',image_management.image_delete,name='image_delete'),

    path('<int:course_pk>/sub_course/list/',sub_course_management.sub_course_list,name='sub_course_list'),
    path('<int:course_pk>/sub_course/add/',sub_course_management.sub_course_add,name='sub_course_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/edit',sub_course_management.sub_course_edit,name='sub_course_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/delete',sub_course_management.sub_course_delete,name='sub_course_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/move_up',sub_course_management.sub_course_move_up,name='sub_course_move_up'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/move_down',sub_course_management.sub_course_move_down,name='sub_course_move_down'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/add',module_management.module_add,name='module_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/edit',module_management.module_edit,name='module_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/delete',module_management.module_delete,name='module_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/move_up',module_management.module_move_up,name='module_move_up'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/move_down',module_management.module_move_down,name='module_move_down'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/sub_module/add',sub_module_management.sub_module_add,name='sub_module_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/sub_module/<int:sub_module_pk>/edit',sub_module_management.sub_module_edit,name='sub_module_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/sub_module/<int:sub_module_pk>/delete',sub_module_management.sub_module_delete,name='sub_module_delete'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/add',quiz_management.quiz_add,name='quiz_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/detail/',quiz_management.quiz_detail,name='quiz_detail'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/edit/',quiz_management.quiz_edit,name='quiz_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/delete/',quiz_management.quiz_delete,name='quiz_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/move_up/',quiz_management.quiz_move_up,name='quiz_move_up'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/move_down/',quiz_management.quiz_move_down,name='quiz_move_down'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/quiz_report_list/',quiz_report_management.quiz_report_list,name='quiz_report_list'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/quiz_report_user/<int:user_pk>/attempt/<int:attempt_pk>/',quiz_report_management.quiz_report_detail,name='quiz_report_detail'),


    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/add',question_management.question_add,name='question_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/delete',question_management.question_delete,name='question_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/edit',question_management.question_edit,name='question_edit'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/answer/add',answer_management.answer_add,name='answer_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/answer/<int:answer_pk>/edit',answer_management.answer_edit,name='answer_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/answer/<int:answer_pk>/delete',answer_management.answer_delete,name='answer_delete'),
    
    
    path('<int:course_pk>',course_operations.short_link_course,name='short_link_course'),
    path('<int:course_pk>/<str:course_name>/preview/',course_operations.course_preview,name='course_preview'),
    path('<int:course_pk>/enroll',course_operations.course_enroll,name='course_enroll'),

    path('<int:course_pk>/learn/<int:sub_module_pk>/',course_operations.short_link_learning_view,name='short_link_learning_view'),
    path('<int:course_pk>/<str:course_name>/learn/<int:sub_module_pk>',course_operations.learning_view,name='learning_view'),

    path('<int:course_pk>/quiz_preview/<int:quiz_pk>/',quiz_operations.short_link_quiz_preview,name='short_link_quiz_preview'),
    path('<int:course_pk>/<str:course_name>/quiz_preview/<int:quiz_pk>',quiz_operations.quiz_preview,name='quiz_preview'),

    path('<int:course_pk>/do_quiz/<int:quiz_pk>/',quiz_operations.short_link_do_quiz,name='short_link_do_quiz'),
    path('<int:course_pk>/<str:course_name>/do_quiz/<int:quiz_pk>/attempt/<int:attempt_pk>/',quiz_operations.do_quiz,name='do_quiz'),

    path('<int:course_pk>/quiz/<int:quiz_pk>/preview/<int:attempt_pk>',quiz_operations.short_link_attempted_quiz_preview,name='short_link_attempted_quiz_preview'),
    path('<int:course_pk>/<str:course_name>/quiz/<int:quiz_pk>/preview/<int:attempt_pk>',quiz_operations.attempted_quiz_preview,name='attempted_quiz_preview'),

    path('<int:course_pk>/<str:course_name>/do_quiz/<int:quiz_pk>/attempt/<int:attempt_pk>/tab_behavior_logger/', logger.tab_behavior_logger, name="tab_behavior_logger"),
    path('<int:course_pk>/<str:course_name>/do_quiz/<int:quiz_pk>/attempt/<int:attempt_pk>/face_detector/', logger.face_detector, name="face_detector"),
]

django_backend/lms_project/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('main.urls')),  # Include the URLs of the main app
    # path('module/', include('module.urls')),         # For module-related views
    path('module_group/', include('module_group.urls')),  
    path('user/', include('user.urls')),             # For user-related views
    path('user_module/', include('user_module.urls')), # For user-module assignments
    path('category/', include('category.urls')),  
    path('question/', include('question.urls')),  
    # path('quiz/', include('quiz.urls')),  
    path('role/', include('role.urls')),  
    path('subject/', include('subject.urls')),  
    path('training_program/', include('training_program.urls')),  
    path('training_program_subjects/', include('training_program_subjects.urls')),    
    
    path('course/', include('course.urls')),  

    path('tools/', include('tools.urls')),  
    # Add more paths for other new apps here
]

django_backend/main/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views  # Import your views from the main app

from django.conf import settings
from django.conf.urls.static import static


app_name = 'main'

urlpatterns = [
    # Your other URL patterns
    path('', views.home, name='home'),
    # Authentication URLs
    path('login/', auth_views.LoginView.as_view(template_name='login.html', next_page='/'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='logout.html', next_page='login'), name='logout'),
    path('logout/', views.logout_view, name="logout"),
    path('run_setup/', views.run_setup, name="run_setup"),
]

django_backend/course/views/answer_management.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from module_group.models import ModuleGroup

from ..forms import Course_Form, Quiz_Form, Question_Form, Answer_Option_Form
from ..models import Course, Quiz, Question, Answer_Option, Sub_Course

from django.contrib.auth.decorators import login_required, user_passes_test
from main.utils.block import block_student


@login_required
@user_passes_test(block_student)
def answer_add(request, course_pk, sub_course_pk, quiz_pk, question_pk):
    course = get_object_or_404(Course, pk=course_pk)
    sub_course = get_object_or_404(Sub_Course, pk=sub_course_pk)
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    question = get_object_or_404(Question, pk=question_pk)

    if request.method == "POST":
        form = Answer_Option_Form(request.POST)

        form.instance.question = question

        if form.is_valid():
            form = form.save()
            Quiz.objects.get(pk=quiz_pk).save()

            return redirect(
                reverse(
                    "course:quiz_detail",
                    kwargs={
                        "course_pk": course_pk,
                        "sub_course_pk": sub_course_pk,
                        "quiz_pk": quiz_pk,
                    },
                )
            )
    else:
        form = Answer_Option_Form()

    context = {
        "form": form,
        "course_pk": course_pk,
        "sub_course_pk": sub_course_pk,
        "quiz_pk": quiz_pk,
    }
    return render(request, "answer_management/answer_form.html", context)


@login_required
@user_passes_test(block_student)
def answer_edit(request, course_pk, sub_course_pk, quiz_pk, question_pk, answer_pk):
    course = get_object_or_404(Course, pk=course_pk)
    sub_course = get_object_or_404(Sub_Course, pk=sub_course_pk)
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    question = get_object_or_404(Question, pk=question_pk)
    answer = get_object_or_404(Answer_Option, pk=answer_pk)

    if request.method == "POST":
        form = Answer_Option_Form(request.POST, instance=answer)

        if form.is_valid():
            form = form.save()
            Quiz.objects.get(pk=quiz_pk).save()

            return redirect(
                reverse(
                    "course:quiz_detail",
                    kwargs={
                        "course_pk": course_pk,
                        "sub_course_pk": sub_course_pk,
                        "quiz_pk": quiz_pk,
                    },
                )
            )
    else:
        form = Answer_Option_Form(instance=answer)

    context = {
        "form": form,
        "course_pk": course_pk,
        "sub_course_pk": sub_course_pk,
        "quiz_pk": quiz_pk,
    }
    return render(request, "answer_management/answer_form.html", context)


@login_required
@user_passes_test(block_student)
def answer_delete(request, course_pk, sub_course_pk, quiz_pk, question_pk, answer_pk):
    course = get_object_or_404(Course, pk=course_pk)
    sub_course = get_object_or_404(Sub_Course, pk=sub_course_pk)
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    question = get_object_or_404(Question, pk=question_pk)
    answer = get_object_or_404(Answer_Option, pk=answer_pk)

    if request.method == "POST":
        answer.delete()
        Quiz.objects.get(pk=quiz_pk).save()

        return redirect(
            reverse(
                "course:quiz_detail",
                kwargs={
                    "course_pk": course_pk,
                    "sub_course_pk": sub_course_pk,
                    "quiz_pk": quiz_pk,
                },
            )
        )

    context = {
        "name": answer.option_text,
        "cancel_link": reverse(
            "course:quiz_detail",
            kwargs={
                "course_pk": course_pk,
                "sub_course_pk": sub_course_pk,
                "quiz_pk": quiz_pk,
            },
        ),
    }
    return render(request, "confirm_delete.html", context)

django_backend/course/views/course_operations.py
"""
    For student activity: enroll, learn, quiz, ...
"""
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.db.utils import IntegrityError

from module_group.models import ModuleGroup

from ..models import Course, Quiz, Question, Answer_Option, Enrolled_course, Module, Sub_Course, Sub_Module

from django.contrib.auth.decorators import login_required
from main.utils.block import custom_user_passes_test, block_unenrolled_student

from .utils import query_all_sub_courses

def short_link_course(request, course_pk):
    course = get_object_or_404(Course, pk=course_pk)
    course_name = course.url()
    return redirect(reverse('course:course_preview', kwargs={'course_pk': course_pk, 'course_name': course_name}))


def course_preview(request, course_pk, course_name):
    course = get_object_or_404(Course, pk=course_pk)
    if course_name != course.url():
        raise Http404("Incorrect course name!")

    created_by = set()

    if request.user.is_authenticated:
        enrolled_users = course.enrolled_users.filter(user= request.user)
        is_enrolled = True if enrolled_users else False
    else:
        is_enrolled = False

    context = {
        "course" : course,
        "created_by" : created_by,
        "is_enrolled" : is_enrolled,
        "sub_courses" : {}
    }

    sub_courses = course.sub_courses.all()
    for sub_course in sub_courses:
        modules = sub_course.modules.all().order_by("order")
        quizzes = sub_course.quizzes.all().order_by("order")
        
        context['sub_courses'][sub_course] = {
            'modules': {},
            'quizzes': quizzes,
        }

        for module in modules:
            sub_modules = module.sub_modules.all().order_by("order")
            created_by.add(module.created_by.full_name)

            context['sub_courses'][sub_course]['modules'][module] = sub_modules

    return render(request, 'course_operations/course_preview.html', context)
    

@login_required
def course_enroll(request, course_pk):
    course = get_object_or_404(Course, pk=course_pk)
    
    try:
        enrolling = Enrolled_course(course= course, user=request.user)
        enrolling.save()
    except IntegrityError:
        pass

    return redirect(reverse('course:short_link_course', kwargs={'course_pk': course_pk}))


@login_required
@custom_user_passes_test(block_unenrolled_student, "course:short_link_course", ["course_pk"])
def short_link_learning_view(request, course_pk, sub_module_pk):
    course = get_object_or_404(Course, pk=course_pk)
    course_name = course.url()
    
    sub_module = get_object_or_404(Sub_Module, pk=sub_module_pk)

    return redirect(reverse('course:learning_view', kwargs={'course_pk': course_pk, 'course_name': course_name, 'sub_module_pk': sub_module_pk}))


@login_required
@custom_user_passes_test(block_unenrolled_student, "course:short_link_course", ["course_pk"])
def learning_view(request, course_pk, course_name, sub_module_pk):
    course = get_object_or_404(Course, pk=course_pk)
    if course_name != course.url():
        raise Http404("Incorrect course name!")
    
    sub_module = get_object_or_404(Sub_Module, pk=sub_module_pk)

    context = {
        "course" : course,
        "sub_module" : sub_module,
        "sub_courses" : {}
    }

    query_all_sub_courses(course, context)

    return render(request, 'course_operations/main_view.html', context)

django_backend/course/views/utils.py
def query_all_sub_courses(course, context:dict):
    sub_courses = course.sub_courses.all()
    for sub_course in sub_courses:
        modules = sub_course.modules.all().order_by("order")
        quizzes = sub_course.quizzes.all().order_by("order")
        
        context['sub_courses'][sub_course] = {
            'modules': {},
            'quizzes': quizzes,
        }

        for module in modules:
            sub_modules = module.sub_modules.all().order_by("order")

            context['sub_courses'][sub_course]['modules'][module] = sub_modules

django_backend/course/templates/quiz_management/quiz_collapse.html
<div class="accordion my-2" id="accordionExample">
  {% for quiz in modules_and_quizzes.quizzes %}
  <div class="card">
    <div class="card-header" id="quiz_heading_{{ quiz.pk }}">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse"
          data-target="#quiz_collapse_{{ quiz.pk }}" aria-expanded="false" aria-controls="quiz_collapse_{{ quiz.pk }}">
          {{ quiz.order }}. {{ quiz.quiz_title }}
        </button>
      </h2>
    </div>
    <div id="quiz_collapse_{{ quiz.pk }}" class="collapse" aria-labelledby="quiz_heading_{{ quiz.pk }}"
      data-parent="#accordionExample">
      <div class="card-body">
        <h4 class="mb-4">Quiz Information</h4>
        <div class="row">
          <div class="col-7">
            <p><strong>Title</strong>: {{ quiz.quiz_title }}</p>
            <p><strong>Description</strong>: {{ quiz.quiz_description }}</p>
            <p><strong>Total Mark</strong>: {{ quiz.total_mark }}</p>
          </div>
          <div class="col-5">
            <p><strong>Created by</strong>: {{ quiz.created_by.full_name }}</p>
            <p><strong>Created At</strong>: {{ quiz.created_at }}</p>
            <p><strong>Updated at</strong>: {{ quiz.updated_at }}</p>
          </div>
        </div>
        <a href="{% url 'course:quiz_detail' course.pk sub_course.pk quiz.pk%}" style="width: 7rem;"
          class="btn btn-primary">Detail</a>
        <a href="{% url 'course:quiz_move_up' course.pk sub_course.pk quiz.pk%}" style="width: 7rem;"
          class="btn btn-success">Move Up</a>
        <a href="{% url 'course:quiz_move_down' course.pk sub_course.pk quiz.pk%}" style="width: 7rem;"
          class="btn btn-warning">Move Down</a>

        <hr>
        <a href="{% url 'course:quiz_report_list' course.pk sub_course.pk quiz.pk%}" class="btn btn-dark">Mark Report</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

django_backend/course/templates/quiz_management/quiz_detail.html
{% extends 'base.html' %}
{% block title %}Course Detail{% endblock %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <h3 class="mb-4">Quiz Information</h3>
    <div class="row">
        <div class="col">
            <p><strong>Title: </strong>{{ quiz.quiz_title }}</p>
            <p><strong>Description: </strong>{{ quiz.quiz_description }}</p>
            <p><strong>Total Mark: </strong>{{ quiz.total_mark }}</p>
            <p><strong>Mark To Pass</strong>: {{ quiz.mark_to_pass }}</p>
            <p><strong>Time Limit</strong>: <span class="time">{{ quiz.time_limit }}</span></p>
        </div>
        <div class="col">
            <p><strong>Created by: </strong>{{ quiz.created_by.full_name }}</p>
            <p><strong>Created At: </strong>{{ quiz.created_at }}</p>
            <p><strong>Updated at: </strong>{{ quiz.updated_at }}</p>
            <p><strong>Using SEB: </strong>{{ quiz.using_seb }}</p>
        </div>
    </div>
    <a href="{% url 'course:quiz_edit' course.pk sub_course.pk quiz.pk%}" style="width: 5rem;"
        class="btn btn-primary">Edit</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="width: 5%;" scope="col">#</th>
                <th style="width: 95%;" scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for question, answers in questions_and_answers.items %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>
                    <h5><strong>Question: </strong>{{question.question_text}}</h5>
                    <p><strong>Type: </strong>{{question.question_type}}</p>
                    <p><strong>Points: </strong>{{question.points}}</p>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th style="width: 5%;" scope="col">#</th>
                                <th style="width: 70%;" scope="col">Answer</th>
                                <th style="width: 15%;" scope="col">Is Correct</th>
                                <th style="width: 10%;" scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for answer in answers %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{answer.option_text}}</td>
                                <td>{{answer.is_correct}}</td>
                                <td>
                                    <div class="dropdown">
                                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button"
                                            data-toggle="dropdown" aria-expanded="false">
                                            ...
                                        </a>
                                        <div class="dropdown-menu">
                                            <a href="{% url 'course:answer_edit' course.pk sub_course.pk quiz.pk question.pk answer.pk %}"
                                                class="dropdown-item">Edit</a>
                                            <a href="{% url 'course:answer_delete' course.pk sub_course.pk quiz.pk question.pk answer.pk %}"
                                                class="dropdown-item">Delete</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <a href="{% url 'course:answer_add' course.pk sub_course.pk quiz.pk question.pk%}" class="btn btn-primary">Add
                        Answer</a>
                    <hr>
                    <a href="{% url 'course:question_edit' course.pk sub_course.pk quiz.pk question.pk%}" class="btn btn-warning">Edit</a>
                    <a href="{% url 'course:question_delete' course.pk sub_course.pk quiz.pk question.pk%}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'course:question_add' course.pk sub_course.pk quiz.pk%}" class="btn btn-primary">Add Question</a>


    <hr>
    <a href="{% url 'course:sub_course_list' course.pk %}" class="btn btn-secondary">Back to sub course List</a>
    <a href="{% url 'course:quiz_delete' course.pk sub_course.pk quiz.pk%}" class="btn btn-danger">Delete This
        Quiz!</a>
</div>
<script src="{% static 'js/time_converter.js' %}"></script>
{% endblock %}

django_backend/course/templates/quiz_management/quiz_list.html
{% extends 'base.html' %}
{% block title %}Course Detail{% endblock %}

{% block content %}
<div class="container mt-4">
    {% include "course_management/nav_tab.html" %}
    <div class="row">
        <div class="col-2">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                {% for quiz in quizzes %}
                <button class="nav-link {% if forloop.counter == 1 %}active{% endif %} text-left w-100 text-truncate"
                    id="quiz_id_{{ quiz.pk }}_tab" data-toggle="pill" data-target="#quiz_id_{{ quiz.pk }}" type="button"
                    role="tab" aria-controls="quiz_id_{{ quiz.pk }}"
                    aria-selected="{% if forloop.counter == 1 %}true{% else %}false{% endif %}">
                    {{ quiz.quiz_title }}
                </button>

                {% endfor %}

            </div>
        </div>
        <div class="col-10">
            <div class="tab-content" id="v-pills-tabContent">
                {% for quiz in quizzes %}
                <div class="tab-pane fade show {% if forloop.counter == 1 %}active{% endif %} pl-4"
                    id="quiz_id_{{ quiz.pk }}" role="tabpanel" aria-labelledby="quiz_id_{{ quiz.pk }}_tab"
                    style="border-left: solid 1px black;">

                    <h3 class="mb-4">Quiz Information</h3>
                    <p><strong>Title</strong>: {{ quiz.quiz_title }}</p>
                    <p><strong>Description</strong>: {{ quiz.quiz_description }}</p>
                    <p><strong>Total Mark</strong>: {{ quiz.total_mark }}</p>
                    <p><strong>Created by</strong>: {{ quiz.created_by.full_name }}</p>
                    <p><strong>Created At</strong>: {{ quiz.created_at }}</p>
                    <p><strong>Updated at</strong>: {{ quiz.updated_at }}</p>

                    <a href="{% url 'course:quiz_detail' course.pk quiz.pk%}" style="width: 5rem;"
                        class="btn btn-primary">Edit</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <a href="{% url 'course:quiz_add' course.pk%}" class="btn btn-primary">Add Quiz</a>
    <a href="{% url 'course:course_list' %}" class="btn btn-secondary">Back</a>
</div>
{% endblock %}

django_backend/course/templates/quiz_management/quiz_report_list.html
{% extends 'base.html' %}
{% block title %}Course Detail{% endblock %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col">
            <p><strong>Title: </strong>{{ quiz.quiz_title }}</p>
            <p><strong>Description: </strong>{{ quiz.quiz_description }}</p>
            <p><strong>Total Mark: </strong>{{ quiz.total_mark }}</p>
            <p><strong>Mark To Pass</strong>: {{ quiz.mark_to_pass }}</p>
        </div>
        <div class="col">
            <p><strong>Created by: </strong>{{ quiz.created_by.full_name }}</p>
            <p><strong>Created At: </strong>{{ quiz.created_at }}</p>
            <p><strong>Updated at: </strong>{{ quiz.updated_at }}</p>
            <p><strong>Time Limit</strong>: <span class="time">{{ quiz.time_limit }}</span></p>
        </div>
    </div>
    <h5 class="mt-4">Student Attempt</h5>
    <table class="table mt-4">
        <thead>
            <tr>
                <th class="col-1">#</th>
                <th class="col-1">User ID</th>
                <th class="col-2">User Name</th>
                <th class="col-3">Date</th>
                <th class="col-1">Times</th>
                <th class="col-1">Duration</th>
                <th class="col-1">Mark</th>
                <th class="col-2"></th>
            </tr>
        </thead>
        <tbody>
            {% for attempt, dict_data in last_attempt_per_user.items %}
            <tr>
                <th scope="row" style="justify-content: center;">{{ forloop.counter }}</th>
                <td>{{ attempt.user.id }}</td>
                <td>{{ attempt.user.full_name }}</td>
                <td>{{ attempt.attempt_date }}</td>
                <td>{{ dict_data.times }}</td>
                <td><span class="time">{{ attempt.duration }}</span></td>
                <td class="{% if attempt.score >= quiz.mark_to_pass %}bg-success{% else %}bg-danger{% endif %}">
                    {{attempt.score }}
                </td>
                <td>
                    <a href="{% url 'course:quiz_report_detail' course.pk sub_course.pk quiz.pk attempt.user.id attempt.id %}">
                        Detail
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-secondary" href="{% url 'course:sub_course_list' course.pk %}">Back</a>
</div>
<script src="{% static 'js/time_converter.js' %}"></script>
{% endblock %}