django_backend/course/urls.py
from django.urls import path
from .views import course_management
from .views import sub_course_management
from .views import module_management
from .views import sub_module_management
from .views import quiz_management
from .views import quiz_report_management
from .views import question_management
from .views import answer_management
from .views import course_operations
from .views import quiz_operations
from .views import image_management

from .views import logger
app_name = 'course'

urlpatterns = [
    path('course_list',course_management.course_list,name='course_list'),

    path('upload_existed_course/',course_management.upload_existed_course,name='upload_existed_course'),
    path('course_add/',course_management.course_add,name='course_add'),
    path('course_edit/<int:course_pk>/',course_management.course_edit,name='course_edit'),
    path('course_delete/<int:course_pk>/',course_management.course_delete,name='course_delete'),
    path('<int:course_pk>/course_view/',course_management.course_view,name='course_view'),

    path('<int:course_pk>/image_list/',image_management.image_list,name='image_list'),
    path('<int:course_pk>/image_add/',image_management.image_add,name='image_add'),
    path('<int:course_pk>/image/<int:image_pk>/delete',image_management.image_delete,name='image_delete'),

    path('<int:course_pk>/sub_course/list/',sub_course_management.sub_course_list,name='sub_course_list'),
    path('<int:course_pk>/sub_course/add/',sub_course_management.sub_course_add,name='sub_course_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/edit',sub_course_management.sub_course_edit,name='sub_course_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/delete',sub_course_management.sub_course_delete,name='sub_course_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/move_up',sub_course_management.sub_course_move_up,name='sub_course_move_up'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/move_down',sub_course_management.sub_course_move_down,name='sub_course_move_down'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/add',module_management.module_add,name='module_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/edit',module_management.module_edit,name='module_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/delete',module_management.module_delete,name='module_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/move_up',module_management.module_move_up,name='module_move_up'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/move_down',module_management.module_move_down,name='module_move_down'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/sub_module/add',sub_module_management.sub_module_add,name='sub_module_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/sub_module/<int:sub_module_pk>/edit',sub_module_management.sub_module_edit,name='sub_module_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/module/<int:module_pk>/sub_module/<int:sub_module_pk>/delete',sub_module_management.sub_module_delete,name='sub_module_delete'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/add',quiz_management.quiz_add,name='quiz_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/detail/',quiz_management.quiz_detail,name='quiz_detail'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/edit/',quiz_management.quiz_edit,name='quiz_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/delete/',quiz_management.quiz_delete,name='quiz_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/move_up/',quiz_management.quiz_move_up,name='quiz_move_up'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/move_down/',quiz_management.quiz_move_down,name='quiz_move_down'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/quiz_report_list/',quiz_report_management.quiz_report_list,name='quiz_report_list'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/quiz_report_user/<int:user_pk>/attempt/<int:attempt_pk>/',quiz_report_management.quiz_report_detail,name='quiz_report_detail'),


    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/add',question_management.question_add,name='question_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/delete',question_management.question_delete,name='question_delete'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/edit',question_management.question_edit,name='question_edit'),

    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/answer/add',answer_management.answer_add,name='answer_add'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/answer/<int:answer_pk>/edit',answer_management.answer_edit,name='answer_edit'),
    path('<int:course_pk>/sub_course/<int:sub_course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/answer/<int:answer_pk>/delete',answer_management.answer_delete,name='answer_delete'),
    
    
    path('<int:course_pk>',course_operations.short_link_course,name='short_link_course'),
    path('<int:course_pk>/<str:course_name>/preview/',course_operations.course_preview,name='course_preview'),
    path('<int:course_pk>/enroll',course_operations.course_enroll,name='course_enroll'),

    path('<int:course_pk>/learn/<int:sub_module_pk>/',course_operations.short_link_learning_view,name='short_link_learning_view'),
    path('<int:course_pk>/<str:course_name>/learn/<int:sub_module_pk>',course_operations.learning_view,name='learning_view'),

    path('<int:course_pk>/quiz_preview/<int:quiz_pk>/',quiz_operations.short_link_quiz_preview,name='short_link_quiz_preview'),
    path('<int:course_pk>/<str:course_name>/quiz_preview/<int:quiz_pk>',quiz_operations.quiz_preview,name='quiz_preview'),

    path('<int:course_pk>/do_quiz/<int:quiz_pk>/',quiz_operations.short_link_do_quiz,name='short_link_do_quiz'),
    path('<int:course_pk>/<str:course_name>/do_quiz/<int:quiz_pk>/attempt/<int:attempt_pk>/',quiz_operations.do_quiz,name='do_quiz'),

    path('<int:course_pk>/quiz/<int:quiz_pk>/preview/<int:attempt_pk>',quiz_operations.short_link_attempted_quiz_preview,name='short_link_attempted_quiz_preview'),
    path('<int:course_pk>/<str:course_name>/quiz/<int:quiz_pk>/preview/<int:attempt_pk>',quiz_operations.attempted_quiz_preview,name='attempted_quiz_preview'),

    path('<int:course_pk>/<str:course_name>/do_quiz/<int:quiz_pk>/attempt/<int:attempt_pk>/tab_behavior_logger/', logger.tab_behavior_logger, name="tab_behavior_logger"),
    path('<int:course_pk>/<str:course_name>/do_quiz/<int:quiz_pk>/attempt/<int:attempt_pk>/face_detector/', logger.face_detector, name="face_detector"),
]

django_backend/lms_project/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import home

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('main.urls')),  # Include the URLs of the main app
    # path('module/', include('module.urls')),         # For module-related views
    path('module_group/', include('module_group.urls')),  
    path('user/', include('user.urls')),             # For user-related views
    path('user_module/', include('user_module.urls')), # For user-module assignments
    path('category/', include('category.urls')),  
    path('question/', include('question.urls')),  
    # path('quiz/', include('quiz.urls')),  
    path('role/', include('role.urls')),  
    path('subject/', include('subject.urls')),  
    path('training_program/', include('training_program.urls')),  
    path('training_program_subjects/', include('training_program_subjects.urls')),    
    
    path('course/', include('course.urls')),  

    path('tools/', include('tools.urls')),  
    # Add more paths for other new apps here
]

django_backend/main/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views  # Import your views from the main app

from django.conf import settings
from django.conf.urls.static import static


app_name = 'main'

urlpatterns = [
    # Your other URL patterns
    path('', views.home, name='home'),
    # Authentication URLs
    path('login/', auth_views.LoginView.as_view(template_name='login.html', next_page='/'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='logout.html', next_page='login'), name='logout'),
    path('logout/', views.logout_view, name="logout"),
    path('run_setup/', views.run_setup, name="run_setup"),
]

django_backend/course/views/answer_management.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from module_group.models import ModuleGroup

from ..forms import Course_Form, Quiz_Form, Question_Form, Answer_Option_Form
from ..models import Course, Quiz, Question, Answer_Option, Sub_Course

from django.contrib.auth.decorators import login_required, user_passes_test
from main.utils.block import block_student


@login_required
@user_passes_test(block_student)
def answer_add(request, course_pk, sub_course_pk, quiz_pk, question_pk):
    course = get_object_or_404(Course, pk=course_pk)
    sub_course = get_object_or_404(Sub_Course, pk=sub_course_pk)
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    question = get_object_or_404(Question, pk=question_pk)

    if request.method == "POST":
        form = Answer_Option_Form(request.POST)

        form.instance.question = question

        if form.is_valid():
            form = form.save()
            Quiz.objects.get(pk=quiz_pk).save()

            return redirect(
                reverse(
                    "course:quiz_detail",
                    kwargs={
                        "course_pk": course_pk,
                        "sub_course_pk": sub_course_pk,
                        "quiz_pk": quiz_pk,
                    },
                )
            )
    else:
        form = Answer_Option_Form()

    context = {
        "form": form,
        "course_pk": course_pk,
        "sub_course_pk": sub_course_pk,
        "quiz_pk": quiz_pk,
    }
    return render(request, "answer_management/answer_form.html", context)


@login_required
@user_passes_test(block_student)
def answer_edit(request, course_pk, sub_course_pk, quiz_pk, question_pk, answer_pk):
    course = get_object_or_404(Course, pk=course_pk)
    sub_course = get_object_or_404(Sub_Course, pk=sub_course_pk)
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    question = get_object_or_404(Question, pk=question_pk)
    answer = get_object_or_404(Answer_Option, pk=answer_pk)

    if request.method == "POST":
        form = Answer_Option_Form(request.POST, instance=answer)

        if form.is_valid():
            form = form.save()
            Quiz.objects.get(pk=quiz_pk).save()

            return redirect(
                reverse(
                    "course:quiz_detail",
                    kwargs={
                        "course_pk": course_pk,
                        "sub_course_pk": sub_course_pk,
                        "quiz_pk": quiz_pk,
                    },
                )
            )
    else:
        form = Answer_Option_Form(instance=answer)

    context = {
        "form": form,
        "course_pk": course_pk,
        "sub_course_pk": sub_course_pk,
        "quiz_pk": quiz_pk,
    }
    return render(request, "answer_management/answer_form.html", context)


@login_required
@user_passes_test(block_student)
def answer_delete(request, course_pk, sub_course_pk, quiz_pk, question_pk, answer_pk):
    course = get_object_or_404(Course, pk=course_pk)
    sub_course = get_object_or_404(Sub_Course, pk=sub_course_pk)
    quiz = get_object_or_404(Quiz, pk=quiz_pk)
    question = get_object_or_404(Question, pk=question_pk)
    answer = get_object_or_404(Answer_Option, pk=answer_pk)

    if request.method == "POST":
        answer.delete()
        Quiz.objects.get(pk=quiz_pk).save()

        return redirect(
            reverse(
                "course:quiz_detail",
                kwargs={
                    "course_pk": course_pk,
                    "sub_course_pk": sub_course_pk,
                    "quiz_pk": quiz_pk,
                },
            )
        )

    context = {
        "name": answer.option_text,
        "cancel_link": reverse(
            "course:quiz_detail",
            kwargs={
                "course_pk": course_pk,
                "sub_course_pk": sub_course_pk,
                "quiz_pk": quiz_pk,
            },
        ),
    }
    return render(request, "confirm_delete.html", context)

django_backend/course/views/course_operations.py
"""
    For student activity: enroll, learn, quiz, ...
"""
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.db.utils import IntegrityError

from module_group.models import ModuleGroup

from ..models import Course, Quiz, Question, Answer_Option, Enrolled_course, Module, Sub_Course, Sub_Module

from django.contrib.auth.decorators import login_required
from main.utils.block import custom_user_passes_test, block_unenrolled_student

from .utils import query_all_sub_courses

def short_link_course(request, course_pk):
    course = get_object_or_404(Course, pk=course_pk)
    course_name = course.url()
    return redirect(reverse('course:course_preview', kwargs={'course_pk': course_pk, 'course_name': course_name}))


def course_preview(request, course_pk, course_name):
    course = get_object_or_404(Course, pk=course_pk)
    if course_name != course.url():
        raise Http404("Incorrect course name!")

    created_by = set()

    if request.user.is_authenticated:
        enrolled_users = course.enrolled_users.filter(user= request.user)
        is_enrolled = True if enrolled_users else False
    else:
        is_enrolled = False

    context = {
        "course" : course,
        "created_by" : created_by,
        "is_enrolled" : is_enrolled,
        "sub_courses" : {}
    }

    sub_courses = course.sub_courses.all()
    for sub_course in sub_courses:
        modules = sub_course.modules.all().order_by("order")
        quizzes = sub_course.quizzes.all().order_by("order")
        
        context['sub_courses'][sub_course] = {
            'modules': {},
            'quizzes': quizzes,
        }

        for module in modules:
            sub_modules = module.sub_modules.all().order_by("order")
            created_by.add(module.created_by.full_name)

            context['sub_courses'][sub_course]['modules'][module] = sub_modules

    return render(request, 'course_operations/course_preview.html', context)
    

@login_required
def course_enroll(request, course_pk):
    course = get_object_or_404(Course, pk=course_pk)
    
    try:
        enrolling = Enrolled_course(course= course, user=request.user)
        enrolling.save()
    except IntegrityError:
        pass

    return redirect(reverse('course:short_link_course', kwargs={'course_pk': course_pk}))


@login_required
@custom_user_passes_test(block_unenrolled_student, "course:short_link_course", ["course_pk"])
def short_link_learning_view(request, course_pk, sub_module_pk):
    course = get_object_or_404(Course, pk=course_pk)
    course_name = course.url()
    
    sub_module = get_object_or_404(Sub_Module, pk=sub_module_pk)

    return redirect(reverse('course:learning_view', kwargs={'course_pk': course_pk, 'course_name': course_name, 'sub_module_pk': sub_module_pk}))


@login_required
@custom_user_passes_test(block_unenrolled_student, "course:short_link_course", ["course_pk"])
def learning_view(request, course_pk, course_name, sub_module_pk):
    course = get_object_or_404(Course, pk=course_pk)
    if course_name != course.url():
        raise Http404("Incorrect course name!")
    
    sub_module = get_object_or_404(Sub_Module, pk=sub_module_pk)

    context = {
        "course" : course,
        "sub_module" : sub_module,
        "sub_courses" : {}
    }

    query_all_sub_courses(course, context)

    return render(request, 'course_operations/main_view.html', context)

django_backend/course/views/utils.py
def query_all_sub_courses(course, context:dict):
    sub_courses = course.sub_courses.all()
    for sub_course in sub_courses:
        modules = sub_course.modules.all().order_by("order")
        quizzes = sub_course.quizzes.all().order_by("order")
        
        context['sub_courses'][sub_course] = {
            'modules': {},
            'quizzes': quizzes,
        }

        for module in modules:
            sub_modules = module.sub_modules.all().order_by("order")

            context['sub_courses'][sub_course]['modules'][module] = sub_modules

django_backend/course/templates/course_management/basic_info_form.html
{% extends 'base.html' %}
{% load form_filters %}
{% block title %}{% if form.instance.pk %}Edit Course{% else %}Add New Course{% endif %}{% endblock %}

{% block content %}
<div class="container mt-4">
    {% load form_filters %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        {{ form.course_name.label_tag }}
                        {{ form.course_name|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        {{ form.description.label_tag }}
                        {{ form.description|add_class:"form-control" }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-group mt-2">
                        Image (should be 16:9 ratio):
                        {{ form.image|add_class:"" }}
                    </div>

                    {% if form.instance and form.instance.image.url %}
                    <img id="imagePreview" src="{{ form.instance.image.url }}" alt="Image Preview" class="w-100 my-2" />

                    {% else %}
                    <img id="imagePreview" src="#" alt="Image Preview" class="w-100 my-2" style="display: none;" />

                    {% endif %}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>

        {% if form.instance.course_name %}
            <a href="{% url 'course:course_view' form.instance.pk %}" class="btn btn-secondary">Back</a>
        {% else %}
            <a href="{% url 'course:course_list' %}" class="btn btn-secondary">Back</a>
        {% endif %}
    </form>

    <script>
        document.querySelector('input[type="file"]').addEventListener('change', function (event) {
            const file = event.target.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    const img = document.getElementById('imagePreview');
                    img.src = e.target.result;
                    img.style.display = 'block';
                }
                reader.readAsDataURL(file);
            }
        });
    </script>
</div>
{% endblock %}

django_backend/course/templates/course_management/course_form.html
{% extends 'base.html' %}
{% load form_filters %}
{% block title %}{% if form.instance.pk %}Edit Course{% else %}Add New Course{% endif %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="basic-info-tab" data-toggle="pill" data-target="#basic-info" type="button" role="tab" aria-controls="basic-info" aria-selected="true">
            Course View
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-profile-tab" data-toggle="pill" data-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">
            Quiz
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-contact-tab" data-toggle="pill" data-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Contact</button>
        </li>
      </ul>
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="basic-info" role="tabpanel" aria-labelledby="basic-info-tab">
            {% include "./basic_info_form.html" %}
        </div>
        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
          {% comment %} {% include "./add_quizz_tab.html" %} {% endcomment %}
        </div>
        <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">...</div>
      </div>
</div>
{% endblock %}

django_backend/course/templates/course_management/course_list.html
{% extends 'base.html' %}
{% block title %}Course List{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Course List</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Course Name</th>
                <th>Description</th>
                <th>Image</th>
                <th>Created At</th>
                <th>Modified At</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
            <tr>
                <td>{{ course.course_name }}</td>
                <td>{{ course.description }}</td>
                <td>
                    <img src="{{ course.image.url }}" style="max-width: 18rem">
                </td>
                <td>{{ course.created_at|date:"Y-m-d" }}</td>
                <td>{{ course.modified_at|date:"Y-m-d" }}</td>
                <td>
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                          ...
                        </a>
                        <div class="dropdown-menu">
                          <a href="{% url 'course:course_view' course.pk %}" class="dropdown-item">Detail</a>
                          <a href="{% url 'course:course_delete' course.pk %}" class="dropdown-item">Delete</a>
                        </div>
                      </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'course:course_add' %}" class="btn btn-primary">Add New Course</a>
    <a href="{% url 'course:upload_existed_course' %}" class="btn btn-primary">Upload Existed Course</a>
</div>
{% endblock %}

django_backend/course/templates/course_management/course_view.html
{% extends 'base.html' %}
{% block title %}Course Detail{% endblock %}

{% block content %}
<div class="container mt-4">
  {% include "nav_tab.html" %}
  <div class="container-fluid mt-4">
    <a class="card mb-3" style="text-decoration: none; color: black;" href="#">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img class="w-100" src="{{ course.image.url }}" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{course.course_name}}</h5>
            <p class="card-text">{{course.description}}</p>
            <p class="card-text"><small class="text-muted">Updated: {{course.modified_at|date:"Y-m-d"}}</small></p>
          </div>
        </div>
      </div>
    </a>
    <a href="{% url 'course:course_edit' course.pk %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'course:course_list' %}" class="btn btn-secondary">Back</a>
  </div>
</div>
{% endblock %}